config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'users/new'
  root 'static#index'
  get  '/help', to: 'static#help'
  get  '/events', to: 'events#index'
  get  '/events/new', to: 'events#new'
  post '/events/new', to: 'events#create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'users', to: 'users#index'

  get '/user/show', to: 'users#show'

  get 'getupcomingevents', to: 'events#get_upcoming_events'
  get 'getpastevents', to: 'events#get_past_events'

  
  
  resources :admins
  resources :customers
  resources :users

  resources :events do
    get  'addcustomer', on: :member, as: 'add'
  end

  # namespace :v1, defaults: { format: 'json' } do
  #   get 'things', to: 'things#index'
  # end

  # get '*page', to: 'static#index', constraints: ->(req) do
  #   !req.xhr? && req.format.html?
  # end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :customerevents, class_name: 'CustomerEvent',  dependent: :delete_all
  has_many :events, through: :customerevents

end

app/models/customer_event.rb
class CustomerEvent < ApplicationRecord
  belongs_to :customer
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  has_many :customerevents, class_name: 'CustomerEvent', dependent: :delete_all
  has_many :customers, through: :customerevents

  default_scope { order("datetime DESC") }
  scope :upcoming, -> {where("datetime >= ?", DateTime.now)}
  scope :previous, -> {where("datetime < ?", DateTime.now)}

  def date_formatted
    if self.datetime
      self.datetime.strftime("%d/%m/%Y")
    else
      self.datetime = DateTime.now.strftime("%d/%m/%Y")
    end
  end

  def time_formatted
    if self.time
      self.time.strftime("%l:%M %P")
    else
      self.time = Time.now.strftime("%l:%M %P")
    end
  end

  def available_tickets
    if self.customers != nil
      self.tickets.to_i - self.customers.count
    end
  end

  def customer_count
    if self.customers == nil || self.customers == 0 
      "No customers are going to this event yet"
    else
      self.customers.count
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

def logged_in_user
  unless logged_in?
    flash[:danger] = "Please log in."
    redirect_to login_url
  end
end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :logged_in_user

  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:success] = "customer added!"
      redirect_to customers_url
    else
      render 'new'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      flash[:success] = "customer updated"
      redirect_to @customer
    else
      render 'addcustomer'
    end
  end

  def destroy
    Customer.find(params[:id]).destroy
    flash[:success] = "Customer deleted"
    redirect_to customers_url
  end


  private

  def customer_params
    params.require(:customer).permit(:name, :email, :phone)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, except: [:get_upcoming_events, :get_past_events]

  def get_upcoming_events
    @events = Event.all.upcoming.map { |e| e.attributes.merge(image: rails_blob_path(e.image), date: e.date_formatted, time: e.time_formatted)}
    render json: { data: @events }

  end

  def get_past_events
    @events = Event.all.previous.map { |e| e.attributes.merge(image: rails_blob_path(e.image), date: e.date_formatted, time: e.time_formatted)}
    render json: { data: @events }

  end

  def index
    @events = Event.all
    @upcoming_events = Event.all.upcoming
    @previous_events = Event.all.previous
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event added!"
      redirect_to events_url
    else
      render 'new'
    end
  end

  def addcustomer
    @event = Event.find(params[:id])
    @customer = Customer.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
      redirect_to @event
    else
      render 'addcustomer'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to events_url
  end

  private

  def event_params
    params.require(:event).permit(:image, :name, :datetime, :time, :location, :tickets, :price, customer_ids:[])
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      puts('nope')
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def show
    render params[:page]
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user

  def show
    @user = User.find(params[:id])
    @upcoming_events = Event.all.upcoming
    @previous_events = Event.all.previous
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Admin user created!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Admin user updated"
      redirect_to @user
    else
      #change this
      render 'addcustomer'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Admin deleted"
    redirect_to users_url
  end

 private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "FanFactory"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_events.html.erb
<% @user.event.each do |event| %>
  <tr>
    <td><%= link_to "#{event.name}", event%></td>
    <td><%= event.datetime %></td>
    <td><%= event.customers.count %></td>
    <td><%= event.tickets %></td>
  </tr>
<% end %>

app/views/application/_footer.html.erb
<%= @user.name %>, <%= @user.email %><br>
<%= link_to "Log out", logout_path, method: :delete %>

app/views/application/_header.html.erb
<nav class="nav navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to image_tag("fanfactory.jpg", class: "img-thumbnail", height: "50px"), root_path %> 
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Eventos
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Nuevo Evento", {controller: "events", action: "new"}, class:"dropdown-item"  %>
      <%= link_to "Todos Los Eventos", {controller: "events", action: "index"}, class:"dropdown-item"  %>
    </div>
  </div>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Clientes
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to "Nuevo Cliente", {controller: "customers", action: "new"}, class:"dropdown-item"  %>
      <%= link_to "Todos Los Clientes", {controller: "customers", action: "index"}, class:"dropdown-item"  %>
    </div>
  </div>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Admin
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Nuevo Admin", {controller: "users", action: "new"}, class:"dropdown-item"  %>
      <%= link_to "Ver/Editar Admins", {controller: "users", action: "index"}, class:"dropdown-item"  %>
    </div>
  </div>
  <%= link_to "Cerrar Sesión", logout_path, method: "delete" %>
</nav>

app/views/application/_home.html.erb
<h1> Welcome <%= @user.name %></h1>
<h2> Upcoming events:</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Ubitacion</th>
      <th>Entradas Vendidas</th>
      <th>Entradas Disponibles</th>
      <th>Entradas Totales</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

<% @upcoming_events.each do |event| %>
  <tr>
    <td><%= link_to "#{event.name}", event%></td>
    <td><%= event.date_formatted %></td>
    <td><%= event.time_formatted %></td>
    <td><%= event.location %></td>
    <td><%= event.customers.count %></td>
    <td><%= event.available_tickets %></td>
    <td><%= event.tickets %></td>
  </tr>
<% end %>
</table>

app/views/customers/edit.html.erb
<% provide(:title, 'Edit Customer') %>
 <%= render 'application/header' %>
  <h1>Edit Customer</h1>

    <%= form_for(@customer) do |f| %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      <%= f.label :phone_number %>
      <%= f.text_field :phone, class: 'form-control' %><br>

      <%= f.submit %>

  <% end %>
</div>
<br>

app/views/customers/index.html.erb
<% provide(:title, 'All Customers') %>
 <%= render 'application/header' %>
  <h1>Customer index</h1>
  <div class="all-events-body">
    </div>
    <div class = "cusindex">
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Numero de Tele</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <% @customer.each do |customer| %>
      <tr>
        <td><%= link_to "#{customer.id}", customer%></td>
        <td><%= link_to "#{customer.name}", customer %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone %></td>
    
      </tr>
    <% end %>
    </table>
    </div>
  </div>



     

app/views/customers/new.html.erb
<% provide(:title, 'New Customer') %>
 <%= render 'application/header' %>
<div class="pagehead">
  <h1>New Customer</h1>
    <%= form_for(@customer) do |f| %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      <%= f.label :phone_number %>
      <%= f.text_field :phone, class: 'form-control' %><br>

      <%= f.submit %>

  <% end %>
</div>
<br>

app/views/customers/show.html.erb
<% provide(:title, @customer.name) %>
 <%= render 'application/header' %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    </section>
  </aside>
  </div>
      <h1>Name: <%= @customer.name %></h1><br>
        <h2>Email: <%= @customer.email %></h2><br>
        <h2>Phone: <%= @customer.phone %></h2><br>
        <h3><%= "Upcoming events for #{@customer.name}: "%><%= @customer.events.upcoming.count %></h3>

        <table>
          <thead>
              <tr>
                <th>Event</th>
                <th>Fecha</th>
                <th colspan="3"></th>
              </tr>
          </thead>

          <% @customer.events.upcoming.each do |event| %>
          <tr>
            <td><%= link_to "#{event.name}", event%></td>
            <td><%= event.date_formatted %></td>
          </tr>
          <%end %>

        
        </table>

        <br>
        <h3><%= "Past events for #{@customer.name}: "%><%= @customer.events.previous.count %></h3>
        <table>
          <thead>
              <tr>
                <th>Event</th>
                <th>Fecha</th>
                <th colspan="3"></th>
              </tr>
          </thead>
          <% @customer.events.previous.each do |event| %>
          <tr>
            <td><%= link_to "#{event.name}", event%></td>
            <td><%= event.date_formatted %></td>
          </tr>
          <%end%>
        </table>
        
     <%= link_to 'Edit', edit_customer_path(@customer) %>
     <br>
    <%= link_to "Delete Customer", @customer, method: :delete,
    data: { confirm: "Are you sure you want to delete #{@customer.name}?" } %>
    <br>

app/views/events/_addcustomerform.html.erb
<%= form_for(@event) do |f| %>
  <%= hidden_field_tag "event[customer_ids][]", nil%>
  <% @customer.each do |customer| %>
    <%= check_box_tag "event[customer_ids][]", customer.id,
     @event.customer_ids.include?(customer.id), id:dom_id(customer) %>
    <%= label_tag dom_id(customer), customer.id %>
    <%= label_tag dom_id(customer), customer.name %> --
    <%= label_tag dom_id(customer), customer.email %> --
    <%= label_tag dom_id(customer), customer.phone %>
    <br>
  <% end %>  
  <br>
  <%= f.submit%>
<% end %>  

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

    <%= f.label :nombre %>
    <%= f.text_field :name, class: 'form-control' %><br>

    <%= f.label :ubicación %>
    <%= f.text_field :location, class: 'form-control' %><br>

    <%= f.label :date %>
    <%= f.date_field :datetime, class: 'form-control' %><br>

    <%= f.label :time %>
    <%= f.time_field :time, class: 'form-control' %><br>

    <%= f.label :entradas_disponibles %>
    <%= f.number_field :tickets, class: 'form-control' %><br>

    <%= f.label :precio %>
    <%= f.number_field :price, step: 0.5, class: 'form-control' %><br>

    <%= f.label "Image" %>
    <br>  
    <% if @event.image.attached? %>
      <%= image_tag(@event.image, class: "event-img") %>
      <br>
    <% end %>
    <%= f.file_field :image %><br>
    <br>

    <%= f.submit %>

  <% end %>

app/views/events/_past.html.erb
<h1>Past events: </h1>

<table>
 <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Ubitacion</th>
      <th>Entradas Vendidas</th>
      <th>Entradas Sin Vender</th>
      <th>Entradas Totales</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>


<% @previous_events.each do |event| %>
  <tr>
    <td><%= link_to "#{event.name}", event%></td>
    <td><%= event.date_formatted %></td>
    <td><%= event.time_formatted %></td>
    <td><%= event.location %></td>
    <td><%= event.customer_count %></td>
    <td><%= event.available_tickets %></td>
    <td><%= event.tickets %></td>
  </tr>
<% end %>
</table>

app/views/events/_upcoming.html.erb
<h1>Upcoming events: </h1>
<div class="all-events-body">
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Ubitacion</th>
        <th>Entradas Vendidas</th>
        <th>Entradas Disponibles</th>
        <th>Entradas Totales</th>
        
        <th colspan="3"></th>
      </tr>
    </thead>

  <% @upcoming_events.each do |event| %>
    <tr>
      <td><%= link_to "#{event.name}", event%></td>
      <% if event.datetime %>
        <td><%= event.date_formatted %></td>
      <% end %>
      <% if event.datetime %>
        <td><%= event.time_formatted %></td>
      <% end %>
      <td><%= event.location %></td>
      <td><%= event.customer_count %></td>
      <td><%= event.available_tickets %></td>
      <td><%= event.tickets %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/events/addcustomer.html.erb
 <%= render 'application/header' %>
   <h1><%= @event.name %></h1>
    <h2><%= @event.datetime %></h2>
    <h3>Add customers: </h3>
<%= render "addcustomerform" %>

app/views/events/edit.html.erb
<% provide(:title, 'Edit Event') %>
 <%= render 'application/header' %>
<h1>Edit Event</h1>
<%= render 'form' %>
<br>

app/views/events/index.html.erb
<% provide(:title, 'All Events') %>

<%= render 'application/header' %>

<%= render 'upcoming' %>
<br>
<%= render 'past' %>

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>
 <%= render 'application/header' %>
  <h1>New Event</h1>
  
  <%= render 'form' %>
</div>
<br>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<%= render 'application/header' %>
  <h1 class="show-title"><%= @event.name %></h1>
  <%= image_tag(@event.image, class: "event-img") if @event.image.attached? %>
  <table>
    <thead>
    <tr>
      <th>Ubitacion</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tr>
      <td><%= @event.location %></td>
      <% if @event.datetime %>
        <td><%= @event.date_formatted %></td>
        <td><%= @event.time_formatted %></td>
      <% end %>
    </tr>
  </table>
  <%= link_to "Edit #{@event.name}", edit_event_path(@event) %>
  <br>
  <%= link_to "Delete Event", @event, method: :delete,
data: { confirm: "Are you sure you want to delete #{@event.name}?" } %>
  </div>
  <br>

  <div class="event-page-customer-show">
    <h3>Clientes confirmados: (<%= @event.customer_count %>)</h3>
    <table>
    <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Numero de Tele</th>
          <th colspan="3"></th>
        </tr>
    </thead>
    <% if @event.customers %>
      <% @event.customers.each do |customer| %>
        <tr>
          <td><%= link_to "#{customer.id}", customer%></td>
          <td><%= link_to "#{customer.name}", customer%></td>
          <td><%= customer.email %></td>
          <td><%= customer.phone %></td>
        </tr>
      <%end%>
    <%end%>

    <div class="auxlinks">
      <br>
      <%= link_to 'Edit/Add Customers', add_event_path(@event) %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'fanfactory.jpg' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_upcoming.html.erb
  <h1>Upcoming events: </h1>
<div class="all-events-body">
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Ubitacion</th>
      <th>Entradas Vendidas</th>
      <th>Entradas Disponibles</th>
      <th>Entradas Totales</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

<% @upcoming_events.each do |event| %>
  <tr>
    <td><%= link_to "#{event.name}", event%></td>
    <td><%= event.date_formatted %></td>
    <td><%= event.time_formatted %></td>
    <td><%= event.location %></td>
    <td><%= event.customer_count %></td>
    <td><%= event.available_tickets %></td>
    <td><%= event.tickets %></td>
  </tr>
<% end %>
</table>
</body>

app/views/users/index.html.erb
<% provide(:title, 'All Admins') %>
<%= render 'application/header' %>
<h1>Showing all Admins</h1>
  <div class="all-events-body">
    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <% @user.each do |user| %>
      <tr>
        <td><%=user.name%></td>
        <td><%= link_to "delete", user, method: :delete,
                                          data: { confirm: "You sure?" } %></td>

      </tr>
    <% end %>
    </table>
  </div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
 <%= render 'application/header' %>
<h1>New Admin User</h1>
  <%= form_for(@user, url: signup_path) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %><br>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %><br>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %><br>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %><br>


    <%= f.submit "Create Admin User", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
 <%= render 'application/header' %>
  <h1 class="user-welcome"> Welcome <%= @user.name %></h1>
</div>
<div class="upcoming-events">
  <%= render 'upcoming' %>
</div>